cloud_threads_server:

  site_name: 'DroneHome'

  site_summary: 'Community of drone enthusiasts who like to help each other.'

  site_description: 'Learn about drones and UAVs, talk with other people also interested in the hobby, discuss laws and regulations, and organize to fly together or lobby your government.'
